# Generated by Django 4.2.7 on 2024-01-12 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Serice',
            new_name='Service',
        ),
    ]
